// src/lib/projects.svelte
<script>
    const ProjectList = [
        {
            title: "Marktris",
            description: "A Tetris clone made in godot. It includes many in-game features to make the game as faithful to modern tetris as possible. This includes 7-bag, wall-kicks, the Super Rotation System, and will soon include more. Web Deployment coming soon...",
            alt: "Tetris Clone Project",
            href: 'https://marktris.markg.dev/',
            images: [
                {
                src: "/ProjectImages/TitleScreen.png",
                alt: "Tetris Title Screen Screenshot",
                width: "400px",
                },
                {
                src: "/ProjectImages/marktrisscreenshot2.png",
                alt: "Tetris Project Screenshot",
                width: "400px",
                }
            ]
        },
        {
            title: "NeonChat",
            description: "Submission for Fullyhacks 2024. Neonchat is a Bluetooth-based direct messaging chatbox that allows seamless communication between devices.",
            alt: 'Fullyhacks24 Submission',
            href: 'https://jowen-ster.github.io/FULLYHACKS_NEONCHAT/',
            images: [
                {
                src: "/ProjectImages/neonchat1.png",
                alt: "NeonChat Home Screen",
                width: "330px",
                },
                {
                src: "/ProjectImages/neonchat2.png",
                alt: "NeonChat Message Screen",
                width: "300px",
                }
            ]
        },
    ];
</script>


<div>
    <h1 class="text-5xl font-bold text-red-600 text-center">
        Projects
    </h1>
</div>
<div class="projectcontainer">
    {#each ProjectList.entries() as [index, item]}
        <div class="project">
            <h3 class="text-4xl font-bold text-white custommargins">
                {item.title}
            </h3>
            <a class="text-white text-center custommargins" href={item.href} target="_blank">
                {item.description}
            </a>
            {#if item.images.length !== 0}
                {#each item.images as image}
                <a class="custommargins">
                <img src={image.src} alt={image.alt} title={image.alt} width={image.width}>
                </a>
                {/each}
            {/if}
        </div>
    {/each}
</div>

<style>
    .projectcontainer {
        /* border-color: red; */
        /* border-width: 2px; */
        display: flex;
        flex-wrap: wrap;
        width: 100%;
        justify-content: space-around;
        margin-bottom: 2rem;
        margin-top: 1rem;
        
    }

    .project {
        border: 10px solid transparent;
        /* border-image: linear-gradient(to bottom left, #E0F0F0, #C0C0E0) 1; */
        border-color: #CFD6E7;
        border-radius: 2rem;
        border-width: 10px;
        display: flex;
        flex-wrap: wrap;
        width: 30%;
        height: 20%;
        background-color: rgba(0,172,193,1);
        justify-content: flex-start;
        align-items: center;
        flex-direction: column;
        background-image: linear-gradient(60deg, rgba(84,58,183,1) 0%, rgba(0,172,193,1) 100%); 

    }

    .custommargins {
        margin-top: 0.5rem;
        margin-bottom: 0.5rem;
    }

    /*Shrinking for mobile*/
    @media (max-width: 768px) {
    .project {
        width: 90%;
    }
    }
</style>

// src/pages/Projects.tsx
import { GitHub, Language } from "@mui/icons-material";
import { Button, Stack, Typography } from "@mui/material";

interface Links {
    Deployment?: string;
    Github?: string;
}

interface Project {
    title: string;
    description: string;
    image_path: string;
    links?: Links;
}

export default function Projects() {
    const projects: Project[] = [
        {
            title: 'DoodleJump Workshop',
            description: 'As part of a beginner-friendly Unity workshop I led, I developed a 2D platformer game inspired by Doodle Jump to teach the fundamentals of game development using Unity and C#.',
            image_path: '/ProjectImages/doodlejump1.png',
            links: {
                Github: 'https://github.com/MarkRyanGarcia/Doodle-Jump-Gamedev-SP25'
            }
        },
        {
            title: 'Marktris',
            description: 'A Tetris clone made in godot. It includes many in-game features to make the game as faithful to modern tetris as possible. This includes 7-bag, wall-kicks, and the Super Rotation System. Warning: Use Chrome for best experience.',
            image_path: '/ProjectImages/marktris.png',
            links: {
                Deployment: 'https://marktris.markg.dev/',
            }
        },
        {
            title: 'NeonChat',
            description: 'Submission for Fullyhacks 2024. Neonchat is a Bluetooth-based direct messaging chatbox that allows seamless communication between devices.',
            image_path: '/ProjectImages/neonchat.png',
            links: {
                Deployment: 'https://jowen-ster.github.io/FULLYHACKS_NEONCHAT/',
                Github: 'https://github.com/JOwen-ster/FULLYHACKS_NEONCHAT',
            }
        },
        {
            title: 'Portolio Site',
            description: "Hey, what's this doing here?",
            image_path: '/ProjectImages/portfolio.png',
            links: {
                Deployment: 'https://markg.dev/',
                Github: 'https://github.com/MarkRyanGarcia/Portfolio'
            }
        },
    ];

    return (
        <Stack spacing={1} sx={{ textAlign: 'center', alignItems: 'center' }}>
            <Typography variant='h3' color='textSecondary' sx={{ py: 2 }}>
                <strong>
                    Check out my <span style={{ color: '#0593ea' }}>Projects!</span>
                </strong>
            </Typography>

            {projects.map((project, index) => {
                const isOdd = index % 2 === 0;
                const backgroundColor = isOdd ? '' : 'rgba(200, 200, 200, 0.25)';

                return (
                    <Stack
                        key={index}
                        sx={{
                            alignItems: 'center',
                            width: '100%',
                            backgroundColor,
                        }}
                    >
                        <Stack sx={{ width: { xs: '70vw', md: '50vw' }, py: 1, px: { xs: 1, md: 0 } }}>
                            <Stack
                                direction={{ xs: 'column', md: `row${isOdd ? '-reverse' : ''}` }}
                                spacing={2}
                                sx={{
                                    alignItems: 'center',
                                    justifyContent: 'center',
                                    textAlign: { xs: 'center', md: 'left' },
                                }}
                            >
                                <Stack spacing={1} sx={{ alignItems: 'center', textAlign: 'center' }}>
                                    <Typography variant='h6'>{project.title}</Typography>
                                    <Typography variant='caption' sx={{ width: { md: '20vw' } }}>
                                        {project.description}
                                    </Typography>
                                    {project.links && (
                                        <Stack direction="row" spacing={2} sx={{ justifyContent: 'center' }}>
                                            {project.links.Deployment && (
                                                <Button
                                                    startIcon={<Language />}
                                                    variant="contained"
                                                    color="info"
                                                    href={project.links.Deployment}
                                                    target="_blank"
                                                >
                                                    Visit Site
                                                </Button>
                                            )}
                                            {project.links.Github && (
                                                <Button
                                                    startIcon={<GitHub />}
                                                    variant="contained"
                                                    color="info"
                                                    href={project.links.Github}
                                                    target="_blank"
                                                >
                                                    Github
                                                </Button>
                                            )}
                                        </Stack>
                                    )}
                                </Stack>
                                <img
                                    src={project.image_path}
                                    alt={`${project.title} image`}
                                    style={{ width: 250, borderRadius: 5 }}
                                />
                            </Stack>
                        </Stack>
                    </Stack>
                );
            })}
        </Stack>
    );
}
